defaults: &defaults
  access_key_id: "AKIAINGF2DYSNFWDVV6Q"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "propertyshare-development"
test:
  <<: *defaults
  bucket: "propertyshare-test"
production:
  <<: *defaults
  bucket: "propertyshare"