development:
  access_key_id: AKIAINGF2DYSNFWDVV6Q
  secret_access_key: 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
  bucket: propertyshare.betapub-bucket
test:
  access_key_id: AKIAINGF2DYSNFWDVV6Q
  secret_access_key: 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
  bucket: propertyshare.betapub-bucket
production:
  access_key_id: AKIAINFFRXLBABQPCUGQ
  secret_access_key: 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
  bucket: propertyshare.prod-img-bucket