defaults: &defaults
  stripe_api_key: sk_test_vrgoidN2eJcdSwwZqM3CoqGA
  stripe_publishable_key: pk_test_qlD5YKLuGpUoId9ZcX7MbCrS

development:
  <<: *defaults
  host_name: 'http://localhost:3000'

test:
  <<: *defaults
  host_name: 'http://localhost:3000'

production:
  stripe_api_key: sk_live_Nl6KT6KkCnBJXyUTSa1dMC1R
  stripe_publishable_key: pk_live_QB51H7laX8mfBh7LvtVrz2di
  host_name: 'http://propertyshare.io'
